apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
spec:
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  gateways:
    enabled: true
    ingress:
      ingress: true
    openshiftRoute:
      enabled: true
  policy:
    type: Mixer
  security:
    controlPlane:
      mtls: true
    dataPlane:
      automtls: false
      mtls: true
  telemetry:
    type: Mixer
  tracing:
    sampling: 10000
    type: Jaeger
  version: v1.1
